### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by jmcrey** [jacotri77/python_intensive_capstone#4]
## Rubric Score
 
### Criteria 1: Valid Python Code
* _Score Level:_ 4/4
* _Comment(s):_ The code included in the Jupyter notebook runs without any issues.
 
### Criteria 2: Implementation of Project Requirements
* _Score Level:_ 4/4 
* _Comment(s):_ Code includes the suite of functions and classes required of it, and calls them in an appropriate order. Also, the code is well formatted, easy to read, and follows many of Python's best practices.
 
### Criteria 3: Software Architecture
* _Score Level:_ 4/4
* _Comment(s):_ Code is separated into distinct classes and functions, each of which are invoked for their own purposes. This is especially apparent in the `TextSample` object and `find_text_similarity` function in that they leverage all the other functions to achieve their goals. Nice separation of function!
 
### Criteria 4: Uses Python Language Features
* _Score Level:_ 4/4
* _Comment(s):_ The code uses language features appropriate -- if a task can be solved with a Python builtin, it is.

### Criteria 5: Produces Accurate Output
* _Score Level:_ 2/4
* _Comment(s):_ Unfortunately, due to [a small bug in the `ngram_creator` function](#3), the code output is not entirely accurate. 
 
### Overall Score: 18/20

Overall, very good job with this project! The only major thing I noticed is that the `ngram_creator` function needed to adjust how it was calculating the range of the list to iterate through so that duplicate entries were not found (more on that [here](#3)). There were also two minor optimizations we could have made to the `get_average_sentence_length()` function (see [here](#1)) and the `TextSample` object (see [here](#3)). 

Besides that, the code was well written, made great use of Python builtin functions, and followed many of Python's best practices. Nice job!

**Comment by jacotri77** [comment]
Thanks for taking the time to look at all this project with so much focus and in-depth, constructive criticism.  This was my first go at a Python project and I appreciate all of the feedback (especially the explaining oh WHY it is a good idea to do x).
